events {}

http {
    upstream account-service {
        server account-service:3001;
    }
    upstream transaction-service {
        server transaction-service:3002;
    }
    upstream fx-service {
        server fx-service:3004;
    }
    upstream payroll-service {
        server payroll-service:3005;
    }
    upstream admin-service {
        server admin-service:3006;
    }

    server {
        listen 80;

        location /accounts/ {
            proxy_pass http://account-service/;
        }

        location /transactions/ {
            proxy_pass http://transaction-service/;
        }

        location /fx/ {
            proxy_pass http://fx-service/;
        }

        location /payroll/ {
            proxy_pass http://payroll-service/;
        }

        location /admin/ {
            proxy_pass http://admin-service/;
        }
    }
}
